### ISSUE TITLE
PICO_SDK_PATH needs to be defined

### ISSUE THREAD

**Issue by ShawnHymel** [edgeimpulse/example-standalone-inferencing-pico#2]
The following command in the README does not define `PICO_SDK_PATH` as needed by the Pico SDK:

```
export PATH="<Path to Pico SDK>:$PATH"
```

Recommend changing this line in the README to:

```
export PICO_SDK_PATH="<Path to Pico SDK>"
```

**Comment by AIWintermuteAI** [comment]
Fixed in https://github.com/edgeimpulse/example-standalone-inferencing-pico/commit/8600785de99d6bb6c3ff843268e06d1a6f3accf6.
